/*
 * generated by Xtext 2.33.0
 */
package org.xtext.example.videoedit.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class VideoEditUiModule extends AbstractVideoEditUiModule {

	public VideoEditUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
