/*
 * generated by Xtext 2.33.0
 */
package org.xtext.example.videoedit.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.example.videoedit.ui.internal.VideoeditActivator;

public class VideoEditUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return VideoeditActivator.getInstance().getInjector("org.xtext.example.videoedit.VideoEdit");
	}

}
