/*
 * generated by Xtext 2.33.0
 */
package org.xtext.example.videoedit.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.example.videoedit.parser.antlr.internal.InternalVideoEditParser;
import org.xtext.example.videoedit.services.VideoEditGrammarAccess;

public class VideoEditParser extends AbstractAntlrParser {

	@Inject
	private VideoEditGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalVideoEditParser createParser(XtextTokenStream stream) {
		return new InternalVideoEditParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Project";
	}

	public VideoEditGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(VideoEditGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
