/*
 * generated by Xtext 2.33.0
 */
package org.xtext.example.videoedit.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class VideoEditAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("org/xtext/example/videoedit/parser/antlr/internal/InternalVideoEdit.tokens");
	}
}
