/*
 * generated by Xtext 2.33.0
 */
package org.xtext.example.videoedit.ide;


/**
 * Use this class to register ide components.
 */
public class VideoEditIdeModule extends AbstractVideoEditIdeModule {
}
