/*
 * generated by Xtext 2.33.0
 */
package org.xtext.example.videoedit.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.example.videoedit.VideoEditRuntimeModule;
import org.xtext.example.videoedit.VideoEditStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class VideoEditIdeSetup extends VideoEditStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new VideoEditRuntimeModule(), new VideoEditIdeModule()));
	}
	
}
