/*
 * generated by Xtext 2.33.0
 */
package org.xtext.example.videoedit.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;
import org.xtext.example.videoedit.ui.internal.VideoeditActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class VideoEditExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(VideoeditActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		VideoeditActivator activator = VideoeditActivator.getInstance();
		return activator != null ? activator.getInjector(VideoeditActivator.ORG_XTEXT_EXAMPLE_VIDEOEDIT_VIDEOEDIT) : null;
	}

}
