/**
 * generated by Xtext 2.33.0
 */
package org.xtext.example.videoedit.videoEdit;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Audio Level</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.videoedit.videoEdit.AudioLevel#getLevel <em>Level</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.videoedit.videoEdit.VideoEditPackage#getAudioLevel()
 * @model
 * @generated
 */
public interface AudioLevel extends EObject
{
  /**
   * Returns the value of the '<em><b>Level</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Level</em>' attribute.
   * @see #setLevel(int)
   * @see org.xtext.example.videoedit.videoEdit.VideoEditPackage#getAudioLevel_Level()
   * @model
   * @generated
   */
  int getLevel();

  /**
   * Sets the value of the '{@link org.xtext.example.videoedit.videoEdit.AudioLevel#getLevel <em>Level</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Level</em>' attribute.
   * @see #getLevel()
   * @generated
   */
  void setLevel(int value);

} // AudioLevel
