/**
 * generated by Xtext 2.33.0
 */
package org.xtext.example.videoedit.videoEdit;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Clip</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.videoedit.videoEdit.Clip#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.example.videoedit.videoEdit.Clip#getSource <em>Source</em>}</li>
 *   <li>{@link org.xtext.example.videoedit.videoEdit.Clip#getSourceIn <em>Source In</em>}</li>
 *   <li>{@link org.xtext.example.videoedit.videoEdit.Clip#getSourceOut <em>Source Out</em>}</li>
 *   <li>{@link org.xtext.example.videoedit.videoEdit.Clip#getTargetPosition <em>Target Position</em>}</li>
 *   <li>{@link org.xtext.example.videoedit.videoEdit.Clip#getAudioLevel <em>Audio Level</em>}</li>
 *   <li>{@link org.xtext.example.videoedit.videoEdit.Clip#getSyncWith <em>Sync With</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.videoedit.videoEdit.VideoEditPackage#getClip()
 * @model
 * @generated
 */
public interface Clip extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.example.videoedit.videoEdit.VideoEditPackage#getClip_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.example.videoedit.videoEdit.Clip#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Source</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Source</em>' attribute.
   * @see #setSource(String)
   * @see org.xtext.example.videoedit.videoEdit.VideoEditPackage#getClip_Source()
   * @model
   * @generated
   */
  String getSource();

  /**
   * Sets the value of the '{@link org.xtext.example.videoedit.videoEdit.Clip#getSource <em>Source</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Source</em>' attribute.
   * @see #getSource()
   * @generated
   */
  void setSource(String value);

  /**
   * Returns the value of the '<em><b>Source In</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Source In</em>' containment reference.
   * @see #setSourceIn(TimeCode)
   * @see org.xtext.example.videoedit.videoEdit.VideoEditPackage#getClip_SourceIn()
   * @model containment="true"
   * @generated
   */
  TimeCode getSourceIn();

  /**
   * Sets the value of the '{@link org.xtext.example.videoedit.videoEdit.Clip#getSourceIn <em>Source In</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Source In</em>' containment reference.
   * @see #getSourceIn()
   * @generated
   */
  void setSourceIn(TimeCode value);

  /**
   * Returns the value of the '<em><b>Source Out</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Source Out</em>' containment reference.
   * @see #setSourceOut(TimeCode)
   * @see org.xtext.example.videoedit.videoEdit.VideoEditPackage#getClip_SourceOut()
   * @model containment="true"
   * @generated
   */
  TimeCode getSourceOut();

  /**
   * Sets the value of the '{@link org.xtext.example.videoedit.videoEdit.Clip#getSourceOut <em>Source Out</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Source Out</em>' containment reference.
   * @see #getSourceOut()
   * @generated
   */
  void setSourceOut(TimeCode value);

  /**
   * Returns the value of the '<em><b>Target Position</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Target Position</em>' containment reference.
   * @see #setTargetPosition(TimeCode)
   * @see org.xtext.example.videoedit.videoEdit.VideoEditPackage#getClip_TargetPosition()
   * @model containment="true"
   * @generated
   */
  TimeCode getTargetPosition();

  /**
   * Sets the value of the '{@link org.xtext.example.videoedit.videoEdit.Clip#getTargetPosition <em>Target Position</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Target Position</em>' containment reference.
   * @see #getTargetPosition()
   * @generated
   */
  void setTargetPosition(TimeCode value);

  /**
   * Returns the value of the '<em><b>Audio Level</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Audio Level</em>' containment reference.
   * @see #setAudioLevel(AudioLevel)
   * @see org.xtext.example.videoedit.videoEdit.VideoEditPackage#getClip_AudioLevel()
   * @model containment="true"
   * @generated
   */
  AudioLevel getAudioLevel();

  /**
   * Sets the value of the '{@link org.xtext.example.videoedit.videoEdit.Clip#getAudioLevel <em>Audio Level</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Audio Level</em>' containment reference.
   * @see #getAudioLevel()
   * @generated
   */
  void setAudioLevel(AudioLevel value);

  /**
   * Returns the value of the '<em><b>Sync With</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Sync With</em>' reference.
   * @see #setSyncWith(Clip)
   * @see org.xtext.example.videoedit.videoEdit.VideoEditPackage#getClip_SyncWith()
   * @model
   * @generated
   */
  Clip getSyncWith();

  /**
   * Sets the value of the '{@link org.xtext.example.videoedit.videoEdit.Clip#getSyncWith <em>Sync With</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Sync With</em>' reference.
   * @see #getSyncWith()
   * @generated
   */
  void setSyncWith(Clip value);

} // Clip
