/**
 * generated by Xtext 2.33.0
 */
package org.xtext.example.videoedit.videoEdit;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Project</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.videoedit.videoEdit.Project#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.example.videoedit.videoEdit.Project#getTracks <em>Tracks</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.videoedit.videoEdit.VideoEditPackage#getProject()
 * @model
 * @generated
 */
public interface Project extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.example.videoedit.videoEdit.VideoEditPackage#getProject_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.example.videoedit.videoEdit.Project#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Tracks</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.videoedit.videoEdit.Track}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Tracks</em>' containment reference list.
   * @see org.xtext.example.videoedit.videoEdit.VideoEditPackage#getProject_Tracks()
   * @model containment="true"
   * @generated
   */
  EList<Track> getTracks();

} // Project
