/**
 * generated by Xtext 2.33.0
 */
package org.xtext.example.videoedit.videoEdit;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Time Code</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.videoedit.videoEdit.TimeCode#getHours <em>Hours</em>}</li>
 *   <li>{@link org.xtext.example.videoedit.videoEdit.TimeCode#getMinutes <em>Minutes</em>}</li>
 *   <li>{@link org.xtext.example.videoedit.videoEdit.TimeCode#getSeconds <em>Seconds</em>}</li>
 *   <li>{@link org.xtext.example.videoedit.videoEdit.TimeCode#getFrames <em>Frames</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.videoedit.videoEdit.VideoEditPackage#getTimeCode()
 * @model
 * @generated
 */
public interface TimeCode extends EObject
{
  /**
   * Returns the value of the '<em><b>Hours</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Hours</em>' attribute.
   * @see #setHours(int)
   * @see org.xtext.example.videoedit.videoEdit.VideoEditPackage#getTimeCode_Hours()
   * @model
   * @generated
   */
  int getHours();

  /**
   * Sets the value of the '{@link org.xtext.example.videoedit.videoEdit.TimeCode#getHours <em>Hours</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Hours</em>' attribute.
   * @see #getHours()
   * @generated
   */
  void setHours(int value);

  /**
   * Returns the value of the '<em><b>Minutes</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Minutes</em>' attribute.
   * @see #setMinutes(int)
   * @see org.xtext.example.videoedit.videoEdit.VideoEditPackage#getTimeCode_Minutes()
   * @model
   * @generated
   */
  int getMinutes();

  /**
   * Sets the value of the '{@link org.xtext.example.videoedit.videoEdit.TimeCode#getMinutes <em>Minutes</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Minutes</em>' attribute.
   * @see #getMinutes()
   * @generated
   */
  void setMinutes(int value);

  /**
   * Returns the value of the '<em><b>Seconds</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Seconds</em>' attribute.
   * @see #setSeconds(int)
   * @see org.xtext.example.videoedit.videoEdit.VideoEditPackage#getTimeCode_Seconds()
   * @model
   * @generated
   */
  int getSeconds();

  /**
   * Sets the value of the '{@link org.xtext.example.videoedit.videoEdit.TimeCode#getSeconds <em>Seconds</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Seconds</em>' attribute.
   * @see #getSeconds()
   * @generated
   */
  void setSeconds(int value);

  /**
   * Returns the value of the '<em><b>Frames</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Frames</em>' attribute.
   * @see #setFrames(int)
   * @see org.xtext.example.videoedit.videoEdit.VideoEditPackage#getTimeCode_Frames()
   * @model
   * @generated
   */
  int getFrames();

  /**
   * Sets the value of the '{@link org.xtext.example.videoedit.videoEdit.TimeCode#getFrames <em>Frames</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Frames</em>' attribute.
   * @see #getFrames()
   * @generated
   */
  void setFrames(int value);

} // TimeCode
