/**
 * generated by Xtext 2.33.0
 */
package org.xtext.example.videoedit.videoEdit;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Track</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.videoedit.videoEdit.Track#getType <em>Type</em>}</li>
 *   <li>{@link org.xtext.example.videoedit.videoEdit.Track#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.example.videoedit.videoEdit.Track#getClips <em>Clips</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.videoedit.videoEdit.VideoEditPackage#getTrack()
 * @model
 * @generated
 */
public interface Track extends EObject
{
  /**
   * Returns the value of the '<em><b>Type</b></em>' attribute.
   * The literals are from the enumeration {@link org.xtext.example.videoedit.videoEdit.TrackType}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' attribute.
   * @see org.xtext.example.videoedit.videoEdit.TrackType
   * @see #setType(TrackType)
   * @see org.xtext.example.videoedit.videoEdit.VideoEditPackage#getTrack_Type()
   * @model
   * @generated
   */
  TrackType getType();

  /**
   * Sets the value of the '{@link org.xtext.example.videoedit.videoEdit.Track#getType <em>Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' attribute.
   * @see org.xtext.example.videoedit.videoEdit.TrackType
   * @see #getType()
   * @generated
   */
  void setType(TrackType value);

  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.example.videoedit.videoEdit.VideoEditPackage#getTrack_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.example.videoedit.videoEdit.Track#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Clips</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.videoedit.videoEdit.Clip}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Clips</em>' containment reference list.
   * @see org.xtext.example.videoedit.videoEdit.VideoEditPackage#getTrack_Clips()
   * @model containment="true"
   * @generated
   */
  EList<Clip> getClips();

} // Track
