/**
 * generated by Xtext 2.33.0
 */
package org.xtext.example.videoedit.videoEdit;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see org.xtext.example.videoedit.videoEdit.VideoEditPackage
 * @generated
 */
public interface VideoEditFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  VideoEditFactory eINSTANCE = org.xtext.example.videoedit.videoEdit.impl.VideoEditFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Project</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Project</em>'.
   * @generated
   */
  Project createProject();

  /**
   * Returns a new object of class '<em>Track</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Track</em>'.
   * @generated
   */
  Track createTrack();

  /**
   * Returns a new object of class '<em>Clip</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Clip</em>'.
   * @generated
   */
  Clip createClip();

  /**
   * Returns a new object of class '<em>Audio Level</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Audio Level</em>'.
   * @generated
   */
  AudioLevel createAudioLevel();

  /**
   * Returns a new object of class '<em>Time Code</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Time Code</em>'.
   * @generated
   */
  TimeCode createTimeCode();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  VideoEditPackage getVideoEditPackage();

} //VideoEditFactory
