/**
 * generated by Xtext 2.33.0
 */
package org.xtext.example.videoedit.videoEdit;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.example.videoedit.videoEdit.VideoEditFactory
 * @model kind="package"
 * @generated
 */
public interface VideoEditPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "videoEdit";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/example/videoedit/VideoEdit";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "videoEdit";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  VideoEditPackage eINSTANCE = org.xtext.example.videoedit.videoEdit.impl.VideoEditPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.example.videoedit.videoEdit.impl.ProjectImpl <em>Project</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.videoedit.videoEdit.impl.ProjectImpl
   * @see org.xtext.example.videoedit.videoEdit.impl.VideoEditPackageImpl#getProject()
   * @generated
   */
  int PROJECT = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROJECT__NAME = 0;

  /**
   * The feature id for the '<em><b>Tracks</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROJECT__TRACKS = 1;

  /**
   * The number of structural features of the '<em>Project</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROJECT_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.videoedit.videoEdit.impl.TrackImpl <em>Track</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.videoedit.videoEdit.impl.TrackImpl
   * @see org.xtext.example.videoedit.videoEdit.impl.VideoEditPackageImpl#getTrack()
   * @generated
   */
  int TRACK = 1;

  /**
   * The feature id for the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRACK__TYPE = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRACK__NAME = 1;

  /**
   * The feature id for the '<em><b>Clips</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRACK__CLIPS = 2;

  /**
   * The number of structural features of the '<em>Track</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRACK_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.example.videoedit.videoEdit.impl.ClipImpl <em>Clip</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.videoedit.videoEdit.impl.ClipImpl
   * @see org.xtext.example.videoedit.videoEdit.impl.VideoEditPackageImpl#getClip()
   * @generated
   */
  int CLIP = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLIP__NAME = 0;

  /**
   * The feature id for the '<em><b>Source</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLIP__SOURCE = 1;

  /**
   * The feature id for the '<em><b>Source In</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLIP__SOURCE_IN = 2;

  /**
   * The feature id for the '<em><b>Source Out</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLIP__SOURCE_OUT = 3;

  /**
   * The feature id for the '<em><b>Target Position</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLIP__TARGET_POSITION = 4;

  /**
   * The feature id for the '<em><b>Audio Level</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLIP__AUDIO_LEVEL = 5;

  /**
   * The feature id for the '<em><b>Sync With</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLIP__SYNC_WITH = 6;

  /**
   * The number of structural features of the '<em>Clip</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLIP_FEATURE_COUNT = 7;

  /**
   * The meta object id for the '{@link org.xtext.example.videoedit.videoEdit.impl.AudioLevelImpl <em>Audio Level</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.videoedit.videoEdit.impl.AudioLevelImpl
   * @see org.xtext.example.videoedit.videoEdit.impl.VideoEditPackageImpl#getAudioLevel()
   * @generated
   */
  int AUDIO_LEVEL = 3;

  /**
   * The feature id for the '<em><b>Level</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AUDIO_LEVEL__LEVEL = 0;

  /**
   * The number of structural features of the '<em>Audio Level</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AUDIO_LEVEL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.videoedit.videoEdit.impl.TimeCodeImpl <em>Time Code</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.videoedit.videoEdit.impl.TimeCodeImpl
   * @see org.xtext.example.videoedit.videoEdit.impl.VideoEditPackageImpl#getTimeCode()
   * @generated
   */
  int TIME_CODE = 4;

  /**
   * The feature id for the '<em><b>Hours</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TIME_CODE__HOURS = 0;

  /**
   * The feature id for the '<em><b>Minutes</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TIME_CODE__MINUTES = 1;

  /**
   * The feature id for the '<em><b>Seconds</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TIME_CODE__SECONDS = 2;

  /**
   * The feature id for the '<em><b>Frames</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TIME_CODE__FRAMES = 3;

  /**
   * The number of structural features of the '<em>Time Code</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TIME_CODE_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link org.xtext.example.videoedit.videoEdit.TrackType <em>Track Type</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.videoedit.videoEdit.TrackType
   * @see org.xtext.example.videoedit.videoEdit.impl.VideoEditPackageImpl#getTrackType()
   * @generated
   */
  int TRACK_TYPE = 5;


  /**
   * Returns the meta object for class '{@link org.xtext.example.videoedit.videoEdit.Project <em>Project</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Project</em>'.
   * @see org.xtext.example.videoedit.videoEdit.Project
   * @generated
   */
  EClass getProject();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.videoedit.videoEdit.Project#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.videoedit.videoEdit.Project#getName()
   * @see #getProject()
   * @generated
   */
  EAttribute getProject_Name();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.videoedit.videoEdit.Project#getTracks <em>Tracks</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Tracks</em>'.
   * @see org.xtext.example.videoedit.videoEdit.Project#getTracks()
   * @see #getProject()
   * @generated
   */
  EReference getProject_Tracks();

  /**
   * Returns the meta object for class '{@link org.xtext.example.videoedit.videoEdit.Track <em>Track</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Track</em>'.
   * @see org.xtext.example.videoedit.videoEdit.Track
   * @generated
   */
  EClass getTrack();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.videoedit.videoEdit.Track#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Type</em>'.
   * @see org.xtext.example.videoedit.videoEdit.Track#getType()
   * @see #getTrack()
   * @generated
   */
  EAttribute getTrack_Type();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.videoedit.videoEdit.Track#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.videoedit.videoEdit.Track#getName()
   * @see #getTrack()
   * @generated
   */
  EAttribute getTrack_Name();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.videoedit.videoEdit.Track#getClips <em>Clips</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Clips</em>'.
   * @see org.xtext.example.videoedit.videoEdit.Track#getClips()
   * @see #getTrack()
   * @generated
   */
  EReference getTrack_Clips();

  /**
   * Returns the meta object for class '{@link org.xtext.example.videoedit.videoEdit.Clip <em>Clip</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Clip</em>'.
   * @see org.xtext.example.videoedit.videoEdit.Clip
   * @generated
   */
  EClass getClip();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.videoedit.videoEdit.Clip#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.videoedit.videoEdit.Clip#getName()
   * @see #getClip()
   * @generated
   */
  EAttribute getClip_Name();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.videoedit.videoEdit.Clip#getSource <em>Source</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Source</em>'.
   * @see org.xtext.example.videoedit.videoEdit.Clip#getSource()
   * @see #getClip()
   * @generated
   */
  EAttribute getClip_Source();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.videoedit.videoEdit.Clip#getSourceIn <em>Source In</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Source In</em>'.
   * @see org.xtext.example.videoedit.videoEdit.Clip#getSourceIn()
   * @see #getClip()
   * @generated
   */
  EReference getClip_SourceIn();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.videoedit.videoEdit.Clip#getSourceOut <em>Source Out</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Source Out</em>'.
   * @see org.xtext.example.videoedit.videoEdit.Clip#getSourceOut()
   * @see #getClip()
   * @generated
   */
  EReference getClip_SourceOut();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.videoedit.videoEdit.Clip#getTargetPosition <em>Target Position</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Target Position</em>'.
   * @see org.xtext.example.videoedit.videoEdit.Clip#getTargetPosition()
   * @see #getClip()
   * @generated
   */
  EReference getClip_TargetPosition();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.videoedit.videoEdit.Clip#getAudioLevel <em>Audio Level</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Audio Level</em>'.
   * @see org.xtext.example.videoedit.videoEdit.Clip#getAudioLevel()
   * @see #getClip()
   * @generated
   */
  EReference getClip_AudioLevel();

  /**
   * Returns the meta object for the reference '{@link org.xtext.example.videoedit.videoEdit.Clip#getSyncWith <em>Sync With</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Sync With</em>'.
   * @see org.xtext.example.videoedit.videoEdit.Clip#getSyncWith()
   * @see #getClip()
   * @generated
   */
  EReference getClip_SyncWith();

  /**
   * Returns the meta object for class '{@link org.xtext.example.videoedit.videoEdit.AudioLevel <em>Audio Level</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Audio Level</em>'.
   * @see org.xtext.example.videoedit.videoEdit.AudioLevel
   * @generated
   */
  EClass getAudioLevel();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.videoedit.videoEdit.AudioLevel#getLevel <em>Level</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Level</em>'.
   * @see org.xtext.example.videoedit.videoEdit.AudioLevel#getLevel()
   * @see #getAudioLevel()
   * @generated
   */
  EAttribute getAudioLevel_Level();

  /**
   * Returns the meta object for class '{@link org.xtext.example.videoedit.videoEdit.TimeCode <em>Time Code</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Time Code</em>'.
   * @see org.xtext.example.videoedit.videoEdit.TimeCode
   * @generated
   */
  EClass getTimeCode();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.videoedit.videoEdit.TimeCode#getHours <em>Hours</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Hours</em>'.
   * @see org.xtext.example.videoedit.videoEdit.TimeCode#getHours()
   * @see #getTimeCode()
   * @generated
   */
  EAttribute getTimeCode_Hours();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.videoedit.videoEdit.TimeCode#getMinutes <em>Minutes</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Minutes</em>'.
   * @see org.xtext.example.videoedit.videoEdit.TimeCode#getMinutes()
   * @see #getTimeCode()
   * @generated
   */
  EAttribute getTimeCode_Minutes();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.videoedit.videoEdit.TimeCode#getSeconds <em>Seconds</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Seconds</em>'.
   * @see org.xtext.example.videoedit.videoEdit.TimeCode#getSeconds()
   * @see #getTimeCode()
   * @generated
   */
  EAttribute getTimeCode_Seconds();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.videoedit.videoEdit.TimeCode#getFrames <em>Frames</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Frames</em>'.
   * @see org.xtext.example.videoedit.videoEdit.TimeCode#getFrames()
   * @see #getTimeCode()
   * @generated
   */
  EAttribute getTimeCode_Frames();

  /**
   * Returns the meta object for enum '{@link org.xtext.example.videoedit.videoEdit.TrackType <em>Track Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Track Type</em>'.
   * @see org.xtext.example.videoedit.videoEdit.TrackType
   * @generated
   */
  EEnum getTrackType();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  VideoEditFactory getVideoEditFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.example.videoedit.videoEdit.impl.ProjectImpl <em>Project</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.videoedit.videoEdit.impl.ProjectImpl
     * @see org.xtext.example.videoedit.videoEdit.impl.VideoEditPackageImpl#getProject()
     * @generated
     */
    EClass PROJECT = eINSTANCE.getProject();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PROJECT__NAME = eINSTANCE.getProject_Name();

    /**
     * The meta object literal for the '<em><b>Tracks</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROJECT__TRACKS = eINSTANCE.getProject_Tracks();

    /**
     * The meta object literal for the '{@link org.xtext.example.videoedit.videoEdit.impl.TrackImpl <em>Track</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.videoedit.videoEdit.impl.TrackImpl
     * @see org.xtext.example.videoedit.videoEdit.impl.VideoEditPackageImpl#getTrack()
     * @generated
     */
    EClass TRACK = eINSTANCE.getTrack();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TRACK__TYPE = eINSTANCE.getTrack_Type();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TRACK__NAME = eINSTANCE.getTrack_Name();

    /**
     * The meta object literal for the '<em><b>Clips</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TRACK__CLIPS = eINSTANCE.getTrack_Clips();

    /**
     * The meta object literal for the '{@link org.xtext.example.videoedit.videoEdit.impl.ClipImpl <em>Clip</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.videoedit.videoEdit.impl.ClipImpl
     * @see org.xtext.example.videoedit.videoEdit.impl.VideoEditPackageImpl#getClip()
     * @generated
     */
    EClass CLIP = eINSTANCE.getClip();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CLIP__NAME = eINSTANCE.getClip_Name();

    /**
     * The meta object literal for the '<em><b>Source</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CLIP__SOURCE = eINSTANCE.getClip_Source();

    /**
     * The meta object literal for the '<em><b>Source In</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CLIP__SOURCE_IN = eINSTANCE.getClip_SourceIn();

    /**
     * The meta object literal for the '<em><b>Source Out</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CLIP__SOURCE_OUT = eINSTANCE.getClip_SourceOut();

    /**
     * The meta object literal for the '<em><b>Target Position</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CLIP__TARGET_POSITION = eINSTANCE.getClip_TargetPosition();

    /**
     * The meta object literal for the '<em><b>Audio Level</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CLIP__AUDIO_LEVEL = eINSTANCE.getClip_AudioLevel();

    /**
     * The meta object literal for the '<em><b>Sync With</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CLIP__SYNC_WITH = eINSTANCE.getClip_SyncWith();

    /**
     * The meta object literal for the '{@link org.xtext.example.videoedit.videoEdit.impl.AudioLevelImpl <em>Audio Level</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.videoedit.videoEdit.impl.AudioLevelImpl
     * @see org.xtext.example.videoedit.videoEdit.impl.VideoEditPackageImpl#getAudioLevel()
     * @generated
     */
    EClass AUDIO_LEVEL = eINSTANCE.getAudioLevel();

    /**
     * The meta object literal for the '<em><b>Level</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute AUDIO_LEVEL__LEVEL = eINSTANCE.getAudioLevel_Level();

    /**
     * The meta object literal for the '{@link org.xtext.example.videoedit.videoEdit.impl.TimeCodeImpl <em>Time Code</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.videoedit.videoEdit.impl.TimeCodeImpl
     * @see org.xtext.example.videoedit.videoEdit.impl.VideoEditPackageImpl#getTimeCode()
     * @generated
     */
    EClass TIME_CODE = eINSTANCE.getTimeCode();

    /**
     * The meta object literal for the '<em><b>Hours</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TIME_CODE__HOURS = eINSTANCE.getTimeCode_Hours();

    /**
     * The meta object literal for the '<em><b>Minutes</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TIME_CODE__MINUTES = eINSTANCE.getTimeCode_Minutes();

    /**
     * The meta object literal for the '<em><b>Seconds</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TIME_CODE__SECONDS = eINSTANCE.getTimeCode_Seconds();

    /**
     * The meta object literal for the '<em><b>Frames</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TIME_CODE__FRAMES = eINSTANCE.getTimeCode_Frames();

    /**
     * The meta object literal for the '{@link org.xtext.example.videoedit.videoEdit.TrackType <em>Track Type</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.videoedit.videoEdit.TrackType
     * @see org.xtext.example.videoedit.videoEdit.impl.VideoEditPackageImpl#getTrackType()
     * @generated
     */
    EEnum TRACK_TYPE = eINSTANCE.getTrackType();

  }

} //VideoEditPackage
