/**
 * generated by Xtext 2.33.0
 */
package org.xtext.example.videoedit.videoEdit.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.example.videoedit.videoEdit.TimeCode;
import org.xtext.example.videoedit.videoEdit.VideoEditPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Time Code</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.videoedit.videoEdit.impl.TimeCodeImpl#getHours <em>Hours</em>}</li>
 *   <li>{@link org.xtext.example.videoedit.videoEdit.impl.TimeCodeImpl#getMinutes <em>Minutes</em>}</li>
 *   <li>{@link org.xtext.example.videoedit.videoEdit.impl.TimeCodeImpl#getSeconds <em>Seconds</em>}</li>
 *   <li>{@link org.xtext.example.videoedit.videoEdit.impl.TimeCodeImpl#getFrames <em>Frames</em>}</li>
 * </ul>
 *
 * @generated
 */
public class TimeCodeImpl extends MinimalEObjectImpl.Container implements TimeCode
{
  /**
   * The default value of the '{@link #getHours() <em>Hours</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getHours()
   * @generated
   * @ordered
   */
  protected static final int HOURS_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getHours() <em>Hours</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getHours()
   * @generated
   * @ordered
   */
  protected int hours = HOURS_EDEFAULT;

  /**
   * The default value of the '{@link #getMinutes() <em>Minutes</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getMinutes()
   * @generated
   * @ordered
   */
  protected static final int MINUTES_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getMinutes() <em>Minutes</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getMinutes()
   * @generated
   * @ordered
   */
  protected int minutes = MINUTES_EDEFAULT;

  /**
   * The default value of the '{@link #getSeconds() <em>Seconds</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSeconds()
   * @generated
   * @ordered
   */
  protected static final int SECONDS_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getSeconds() <em>Seconds</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSeconds()
   * @generated
   * @ordered
   */
  protected int seconds = SECONDS_EDEFAULT;

  /**
   * The default value of the '{@link #getFrames() <em>Frames</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getFrames()
   * @generated
   * @ordered
   */
  protected static final int FRAMES_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getFrames() <em>Frames</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getFrames()
   * @generated
   * @ordered
   */
  protected int frames = FRAMES_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected TimeCodeImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return VideoEditPackage.Literals.TIME_CODE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getHours()
  {
    return hours;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setHours(int newHours)
  {
    int oldHours = hours;
    hours = newHours;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, VideoEditPackage.TIME_CODE__HOURS, oldHours, hours));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getMinutes()
  {
    return minutes;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setMinutes(int newMinutes)
  {
    int oldMinutes = minutes;
    minutes = newMinutes;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, VideoEditPackage.TIME_CODE__MINUTES, oldMinutes, minutes));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getSeconds()
  {
    return seconds;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setSeconds(int newSeconds)
  {
    int oldSeconds = seconds;
    seconds = newSeconds;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, VideoEditPackage.TIME_CODE__SECONDS, oldSeconds, seconds));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getFrames()
  {
    return frames;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setFrames(int newFrames)
  {
    int oldFrames = frames;
    frames = newFrames;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, VideoEditPackage.TIME_CODE__FRAMES, oldFrames, frames));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case VideoEditPackage.TIME_CODE__HOURS:
        return getHours();
      case VideoEditPackage.TIME_CODE__MINUTES:
        return getMinutes();
      case VideoEditPackage.TIME_CODE__SECONDS:
        return getSeconds();
      case VideoEditPackage.TIME_CODE__FRAMES:
        return getFrames();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case VideoEditPackage.TIME_CODE__HOURS:
        setHours((Integer)newValue);
        return;
      case VideoEditPackage.TIME_CODE__MINUTES:
        setMinutes((Integer)newValue);
        return;
      case VideoEditPackage.TIME_CODE__SECONDS:
        setSeconds((Integer)newValue);
        return;
      case VideoEditPackage.TIME_CODE__FRAMES:
        setFrames((Integer)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case VideoEditPackage.TIME_CODE__HOURS:
        setHours(HOURS_EDEFAULT);
        return;
      case VideoEditPackage.TIME_CODE__MINUTES:
        setMinutes(MINUTES_EDEFAULT);
        return;
      case VideoEditPackage.TIME_CODE__SECONDS:
        setSeconds(SECONDS_EDEFAULT);
        return;
      case VideoEditPackage.TIME_CODE__FRAMES:
        setFrames(FRAMES_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case VideoEditPackage.TIME_CODE__HOURS:
        return hours != HOURS_EDEFAULT;
      case VideoEditPackage.TIME_CODE__MINUTES:
        return minutes != MINUTES_EDEFAULT;
      case VideoEditPackage.TIME_CODE__SECONDS:
        return seconds != SECONDS_EDEFAULT;
      case VideoEditPackage.TIME_CODE__FRAMES:
        return frames != FRAMES_EDEFAULT;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (hours: ");
    result.append(hours);
    result.append(", minutes: ");
    result.append(minutes);
    result.append(", seconds: ");
    result.append(seconds);
    result.append(", frames: ");
    result.append(frames);
    result.append(')');
    return result.toString();
  }

} //TimeCodeImpl
