/*
 * generated by Xtext 2.33.0
 */
package org.xtext.example.videoedit.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractVideoEditValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(org.xtext.example.videoedit.videoEdit.VideoEditPackage.eINSTANCE);
		return result;
	}
}
