/*
 * generated by Xtext 2.33.0
 */
package org.xtext.example.videoedit;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class VideoEditStandaloneSetup extends VideoEditStandaloneSetupGenerated {

	public static void doSetup() {
		new VideoEditStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
