/*
 * generated by Xtext 2.33.0
 */
package org.xtext.example.videoedit.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractVideoEditScopeProvider extends DelegatingScopeProvider {
}
